/*
  ==============================================================================

    This file was auto-generated by the Introjucer!

    It contains the basic framework code for a JUCE plugin editor.

  ==============================================================================
*/

#include "DelayOperatorComponent.h"
#include "DelayPluginEditor.h"


//==============================================================================
TestProject5AudioDelayProcessorEditor::TestProject5AudioDelayProcessorEditor (DelayOperatorContentComponent& p)
    : AudioProcessorEditor (&p), processor (p)
{
    // Make sure that before the constructor has finished, you've set the
    // editor's size to whatever you need it to be.
    setSize (400, 300);
}

TestProject5AudioDelayProcessorEditor::~TestProject5AudioDelayProcessorEditor()
{
}

//==============================================================================
void TestProject5AudioDelayProcessorEditor::paint (Graphics& g)
{
    g.fillAll (Colours::white);

    g.setColour (Colours::black);
    g.setFont (15.0f);
    g.drawFittedText ("Hello World!", getLocalBounds(), Justification::centred, 1);
}

void TestProject5AudioDelayProcessorEditor::resized()
{
    // This is generally where you'll want to lay out the positions of any
    // subcomponents in your editor..
}
