/*
  ==============================================================================

    This file was auto-generated by the Introjucer!

    It contains the basic framework code for a JUCE plugin editor.

  ==============================================================================
*/

#ifndef DELAYPLUGINEDITOR_H_INCLUDED
#define DELAYPLUGINEDITOR_H_INCLUDED

#include "../JuceLibraryCode/JuceHeader.h"
#include "DelayOperatorComponent.h"


//==============================================================================
/**
*/
class TestProject5AudioDelayProcessorEditor  : public AudioProcessorEditor
{
public:
    TestProject5AudioDelayProcessorEditor (DelayOperatorContentComponent&);
    ~TestProject5AudioDelayProcessorEditor();

    //==============================================================================
    void paint (Graphics&) override;
    void resized() override;

private:
    // This reference is provided as a quick way for your editor to
    // access the processor object that created it.
    DelayOperatorContentComponent& processor;

    JUCE_DECLARE_NON_COPYABLE_WITH_LEAK_DETECTOR (TestProject5AudioDelayProcessorEditor)
};


#endif  // DELAYPLUGINEDITOR_H_INCLUDED
