/*
  ==============================================================================

    This file was auto-generated by the Introjucer!

    It contains the basic framework code for a JUCE plugin editor.

  ==============================================================================
*/

#ifndef SAMPLER1PLUGINEDITOR_H_INCLUDED
#define SAMPLER1PLUGINEDITOR_H_INCLUDED

#include "../JuceLibraryCode/JuceHeader.h"
#include "Sampler1OperatorComponent.h"


//==============================================================================
/**
*/
class TestProject5AudioSampler1ProcessorEditor  : public AudioProcessorEditor
{
public:
    TestProject5AudioSampler1ProcessorEditor (Sampler1OperatorContentComponent&);
    ~TestProject5AudioSampler1ProcessorEditor();

    //==============================================================================
    void paint (Graphics&) override;
    void resized() override;

private:
    // This reference is provided as a quick way for your editor to
    // access the processor object that created it.
    Sampler1OperatorContentComponent& processor;

    JUCE_DECLARE_NON_COPYABLE_WITH_LEAK_DETECTOR (TestProject5AudioSampler1ProcessorEditor)
};


#endif  // SAMPLER1PLUGINEDITOR_H_INCLUDED
