/*
  ==============================================================================

    This file was auto-generated by the Introjucer!

    It contains the basic framework code for a JUCE plugin editor.

  ==============================================================================
*/

#ifndef TREMOLOPLUGINEDITOR_H_INCLUDED
#define TREMOLOPLUGINEDITOR_H_INCLUDED

#include "../JuceLibraryCode/JuceHeader.h"
#include "TremoloOperatorComponent.h"


//==============================================================================
/**
*/
class TestProject5AudioTremoloProcessorEditor  : public AudioProcessorEditor
{
public:
    TestProject5AudioTremoloProcessorEditor (TremoloOperatorContentComponent&);
    ~TestProject5AudioTremoloProcessorEditor();

    //==============================================================================
    void paint (Graphics&) override;
    void resized() override;

private:
    // This reference is provided as a quick way for your editor to
    // access the processor object that created it.
    TremoloOperatorContentComponent& processor;

    JUCE_DECLARE_NON_COPYABLE_WITH_LEAK_DETECTOR (TestProject5AudioTremoloProcessorEditor)
};


#endif  // TREMOLOPLUGINEDITOR_H_INCLUDED
